### ISSUE TITLE
Text differences in invalid and not_found_in_database for en and en-GB

### ISSUE THREAD

**Issue by awaltman** [tigrish/devise-i18n#114]
I noticed that for both en.yml and en-GB.yml that the text for devise.failure.invalid and devise.failure.not_found_in_database do not match which I think is inconsistent. Also, the Devise version of this string includes a placeholder for the type of key:

"Invalid %{authentication_keys} or password."

I think it would be better to have en and en-GB translations updated to use the same text and if  possible also use the place holder.

Thanks,
Andrew

**Comment by JasonBarnabe** [comment]
Good catch, but I think that doing so would mean dropping support for any version of devise before [this commit](https://github.com/plataformatec/devise/commit/6b0d11ed7a457ef1a338718e2e1819aeb25e943d). Not sure it's worth it at this point.

**Comment by gdurelle** [comment]
That's the point of GIT. 
It doesn't break things because you choose to use the proper tagged version. 
Otherwise you would never update anything.

**Comment by JasonBarnabe** [comment]
This gem maintains backwards compatibility so that when translations are added and updated, they are available to users using an older version of devise. The gem actually does not even require a specific version of devise.

It could be that it's time to make the jump to requiring a newer version of devise. Or multiple branches could be maintained. Or some fanciness could happen to choose the correct file based on the version used. I'm open to all these options, but this string change seems pretty minor, and I'm not sure it's worth it.

**Comment by JasonBarnabe** [comment]
[This devise change came in 3.4.0.](https://github.com/plataformatec/devise/commit/6b0d11ed7a457ef1a338718e2e1819aeb25e943d) I have added a minimum of devise 2 in devise-i18n 1.3.0. In an upcoming version I will up the minimum to 3.4.0 and include this change.

**Comment by JasonBarnabe** [comment]
This will be in 1.5.0.
